### ISSUE TITLE
Consider: Include "updated location metadata" to Recent Activity filter

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#192]
Jeez, I totally forgot to include this User Submission category.

I'm not even certain if we want it. But we can consider it.

Basically, when a phone number/website/operator/description is updated, we'd have a Recent Activity item that says, "User updated the location info at Location_Name."

**Comment by bpoore** [comment]
That is super easy to include from the perspective of the app. We would need to confirm / possibly refine the sentences coming back is the only concern. 

We would just include the type of `location_metadata` here: https://github.com/bpoore/pbm-react/blob/master/app/screens/RecentActivity.js#L45 `

**Comment by RyanTG** [comment]
Cool. I'll explore this a bit more. But it might be a big hassle to refine the sentences. Right now, they list all of the fields, regardless of if those fields were updated.

Example: 
````
Changed phone # to 760-827-3200 
Changed website to https://grandpacificresorts.com/ 
Changed operator to Area Amusements 
Changed location type to Resort to Grand Pacific Palisades Resort 
````

Oh, and there's also location description.
````
Changed location description to All machines are (except Munsters) are 50 cents / 5 plays $2. Free pinball on Monday nights. to Vegga's Pub 
````

**Comment by RyanTG** [comment]
Not going to make this change on the pbm side.
