### ISSUE TITLE
Machine update in activity feed redirects to location, not machine

### ISSUE THREAD

**Issue by metroshica** [pinballmap/pbm-react#231]
Currently, when you select a message in the activity feed, the app redirects you to the location. It may be better for machine-related updates (or at least ones with updated notes) to redirect the user directly to the entry for the machine mentioned. This is especially helpful for messages that are too long to fit in the activity feed or for locations with lots of machines. Ran into this when trying to read a long update for a location with 40 machines.

**Comment by bpoore** [comment]
That's a good point. One concern concern is that the flow might feel funky- going to the location screen from recent activity, the user is able to select the machine to see the machine detail screen or go back to the recent activity screen. If we go straight to the machine screen, there isn't a clear path to see the location screen. It seems to come down to- would people rather have to scroll through more machines in the case of locations having many machines or have to go find the location on the map after looking at a machine detail screen?

**Comment by RyanTG** [comment]
I don’t have much to add right now, but I wanted to note that I misinterpreted Landon’s comment, and thought he meant that the user should be directed to the Location Details screen but auto-scrolled down to that particular machine in the list of machines. Didn’t realize he was talking about being sent directly to the Machine Details screen.

**Comment by RyanTG** [comment]
Closing for now. I think it would be too jarring to jump straight into machine details from recent activity. We could consider auto-scrolling down in location details to the particular machine name. But this issue has been sitting for a while and it's not something others have noted, so closing for the sake of cleaning up old and stale issues.
