### ISSUE TITLE
Deep links

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#237]
Brendan from Pindigo mentioned that each of the locations on their app had a deep link (example: https://pindigoapp.com/s/mFc577n8). If you have the app installed, then that link will launch the app and go to the appropriate page. 

Would be sweet to have this. We already have location IDs, so it seems like that would be the unique identifier. Our web links look like https://pinballmap.com/ca-central/?by_location_id=12411

Would be neat if that exact link would open up the app if you have it installed. I dunno what’s involved to get this going, but obviously it also would involve updates to the website/API.

**Comment by RyanTG** [comment]
Deep linking is part of React Navigation: https://reactnavigation.org/docs/en/deep-linking.html

I would think that using react nav is the way to go, but just in case it isn't, here are two other options:

This is also popular: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution
And another one: https://github.com/Starotitorov/react-native-deep-link

**Comment by RyanTG** [comment]
@bpoore I know you said that there were some issues with deep links.

But @alberttwong had a suggestion for a "share" link, where you share a location via imessage (or the equivalent in Android). Not sure if that suggestion fits within this issue, or a new one. Or if it's possible for us to implement.

But it's something to explore.

**Comment by alberttwong** [comment]
I'm thinking much more simple.   Very much how people share restaurant via imessage on Yelp.

**Comment by RyanTG** [comment]
Can you show us an example of this? Like a screenshot?

**Comment by bpoore** [comment]
I think we could use <a href="https://facebook.github.io/react-native/docs/share">this</a>. Depending on the effort involved to get deeplinks in our project, one option would be to link to the pbm website with the location... though it'd be really nice to have deeplinks roll out at the same time if they're possible.

**Comment by RyanTG** [comment]
Resource I just found: https://arsfutura.com/magazine/deep-linking-in-react-native/

**Comment by RyanTG** [comment]
Notes: we're using this branch for this, and are making progress. https://github.com/bpoore/pbm-react/tree/universal-link

We are making use of the existing links.

It is tricky to get the [AASA](https://docs.expo.io/workflow/linking/#aasa-configuration) to use paths that contain queries. And it's not possible for the Android Intent Filters to use them. So, right now it's not looking like we'll be able to say, "use universal links on _these_ urls, but not these other ones." For example, there's no simple way to say, "enable universal links for /map, /portland, /seattle, and the other 99 region paths, and ONLY for direct locations details links, and do not enable them for https://pinballmap.com/portland?utf8=%E2%9C%93&region=portland&by_city_id=Beaverton"

So I think our current course is to simply enable universal links for `/` (e.g., all paths), and then try our best to match them to the app. And if any do not match, such as those other search queries, then we need to _do something_ on the app.

**For now, I'm going to match these website urls with our app:**

https://pinballmap.com/users/13/profile (anything that has "profile") = UserProfile
https://pinballmap.com/store = We're not allowed to have a store on the app, so we'll use About
https://pinballmap.com/faq = FAQ
https://pinballmap.com/portland/about = this is our Contact page, so Contact
https://pinballmap.com/app = Map
https://pinballmap.com/portland/events = Events
https://pinballmap.com/suggest = SuggestLocation
https://pinballmap.com/saved = Saved
https://pinballmap.com/users/login = Login
https://pinballmap.com/users/join = Signup
https://pinballmap.com/users/confirmation/new = ResendConfirmation
https://pinballmap.com/users/password/new = PasswordReset


**Unknown ones:**
https://pinballmap.com/flier
https://pinballmap.com/portland/high_rollers

**Comment by RyanTG** [comment]
Three additional searches that would be nice to account for. All are related to regional/geographical searches that pull up multiple locations. So the goal would be to load the Map screen, centered on this geography.

1) "address=" query, a la https://pinballmap.com/map?utf8=%E2%9C%93&address=Raleigh%2C+NC

2) "by_city_id=". a la https://pinballmap.com/seattle?utf8=%E2%9C%93&region=seattle&by_city_id=Auburn

3) "region=" query. like region=seattle

**Comment by bpoore** [comment]
@RyanTG, I pushed up to [the universal-link branch](https://github.com/bpoore/pbm-react/compare/universal-link) updates that allow for the Map screen to be centered in different locations depending on the incoming url. This could all use some more testing as there's a fair amount of nuanced logic to get this to all work coupled with how we are dealing with two different scenarios to link into the app (when the app is being fired up and when the app is merely backgrounded). 

I think I caught the majority of things that could go wrong with these more involved query strings, but I it's possible I missed some things with that too. For instance- in the following query: https://pinballmap.com/seattle?utf8=%E2%9C%93&region=seattle&by_city_id=Auburn, do we know we will always have `region=` in the query string? We are currently depending on that to be present. Additionally, it appears we expect the city name to be capitalized... I ended up pulling up results for the region in the url if for some reason we don't get back results for the city id in the url.

**Comment by bpoore** [comment]
Also @RyanTG, feel free to update the text/styles/placement of the `Share Location` location button / Share Screen on the location details screen.

**Comment by RyanTG** [comment]
If you're doing a search on a regional map (like /portland or /seattle), then it will always include the `region=` (as far as I know). If you're doing an address search on /map, then it will not (and it won't always be capitalized. It'll just be whatever the person typed). But on a regional map, the query always uses a value from a dropdown list, and will always be capitalized.

This week I'll check out the `Share Location` style. And we can make some builds and test in testflight and android. Thanks for working on this!!!

**Comment by RyanTG** [comment]
Some links for testing:

https://pinballmap.com/iowa

https://pinballmap.com/austin/?by_location_id=6805

https://pinballmap.com/map/?by_location_id=11043

https://pinballmap.com/seattle?utf8=%E2%9C%93&region=seattle&by_city_id=Auburn

**Comment by RyanTG** [comment]
For our records, this looks like a good deep link resource https://gist.github.com/anhar/6d50c023f442fb2437e1

**Comment by RyanTG** [comment]
More links to test 

https://pinballmap.com/map/?by_location_id=9631

https://pinballmap.com/la/?by_location_id=9631

**Comment by RyanTG** [comment]
Re-opening, unfortunately. This doesn't seem to be working right now, at least on iOS. Unclear why at this time.

**Comment by RyanTG** [comment]
Hmm, actually now it’s fixed on ios. Either the 5.2.13 updates did it, or a change I made to the AASA (that didn’t take effect immediately).
