### ISSUE TITLE
Feature Request: Recent Activity for each location.

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#255]
> Feature request: 
> Change log. When viewing a location, it shows when it was last edited. It would be cool if “Last Edited” was a link to a running change log that shows when tables have been added or removed from that location.

This is a pretty good suggestion. Seems like we are already capturing and storing the data... we'd just need to filter it for that location? It'd be Recent Activity, but filtered.

Not sure if we could do this without having to do stuff on the website.

**Comment by bpoore** [comment]
Note for us about the structure of the response form of the response from `GET /api/v1/user_submissions/list_within_range.json`: 

![Screen Shot 2020-01-14 at 11 20 37 AM](https://user-images.githubusercontent.com/7720282/72375119-5cfe1e80-36c0-11ea-9a64-795e8c6d7a8e.png)

We are getting the location_id in the response here. This should be feasible. We're not capturing and storing the data for recent activity, rather gathering it when we go to the Recent Activity screen, but we could make that same call filtering down to the location the user is coming from. The data at this endpoint only covers the last 30 days, so it is highly likely that many locations will not have any activity to show.

**Comment by RyanTG** [comment]
My take:

- I think the only submission_types we should care about in a location history are: remove_machine, add_machine. Cuz who cares if people are confirming or leaving comments, right?
- 30 days is not great. I think we want a longer history here. I'm not sure the best way to go about that. An entirely separate endpoint?

**Comment by RyanTG** [comment]
Endpoint: https://github.com/pinballmap/pbm/commit/0c79c425455cd3bd3c293431980b258c702c3412

Example: https://pinballmap.com/api/v1/user_submissions/location.json?id=888

**Comment by RyanTG** [comment]
What I'm about to write is going sound complicated.

I added the following new fields to the user_submissions table:

> "comment",
> "user_name",
> "location_name",
> "machine_name",
> "high_score"

For "comment" and "high_score", those fields will be EMPTY on all the existing user submissions, but will be populated as new user submissions are created.

For "user_name", "location_name", "machine_name" - I populated those (at least most of them - for example I couldn't populate location_name if the location has been deleted). See https://github.com/pinballmap/pbm/issues/1500 for the psql commands.

**What this means:**

If we want to use these new fields, we need to "build" the sentences differently depending on the submission_type, and we need to include logic that is like, "if ${comment} is nil, then just use the "${user_submission} field instead"

submission_type:

  NEW_LMX

`${machine_name} added by ${user_name}`

  NEW_CONDITION

  REMOVE_MACHINE


  NEW_SCORE

  CONFIRM_LOCATION
