### ISSUE TITLE
Keep tabs on Apple Maps parity with Google Maps in react-native-maps

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#345]
v.29 released 2 days ago. I don't think we can even use this yet. But I'm guessing soon. I was checking out the changelog to see if anything's interesting.

v.29 changelog: https://github.com/react-native-maps/react-native-maps/commit/77cfbaa490c2409d8fb84faf305b3660833a1390

The issue for the apple maps theme settings: https://github.com/react-native-maps/react-native-maps/pull/3764

Seems like it would be cool to use Apple Maps on apple devices.

(btw, I switched to apple maps on my phone to test if the map jerkiness issue occurs there, and it does)

**Comment by RyanTG** [comment]
@bpoore  Looks like we can install v.29 via npm now. I think it would be to use apple maps on iOS and use the new dark/light toggle linked above.

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/389

**Comment by bpoore** [comment]
Noting here so this isn't lost. Currently, with Apple Maps, we are back to seeing: 
<img width="210" alt="Screen Shot 2021-09-14 at 3 56 29 PM" src="https://user-images.githubusercontent.com/7720282/133345410-16d18900-e0fa-4f18-a719-984d364683e3.png">

This causes the `Search this area` button to never show. We may need to go back to google maps until `isGesture` works with Apple Maps.

**Comment by RyanTG** [comment]
Watching: 
https://github.com/react-native-maps/react-native-maps/issues/4112

**Comment by RyanTG** [comment]
I don’t think isGesture will get added. I created a discussion about it, but no traction. Closing this.

https://github.com/react-native-maps/react-native-maps/discussions/4440
