### ISSUE TITLE
Try EAS when it's released

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#346]
Once Expo EAS is free, then we should try it again. One of the benefits is that we'll be able to use modules that aren't part of expo. 

For example, we might be able to switch from react-native-maps to the mapbox one. 

Here's the latest mapbox one https://github.com/react-native-mapbox-gl/maps
They seem to be "getting it ready" for EAS right now.

EDIT: what am I thinking? That would require a mapbox token and probably $$.

**Comment by RyanTG** [comment]
EAS is released! Expo Build is now in maintenance mode and will be sunset by June 2022.

Build instructions: https://docs.expo.dev/build/setup/
Update the cli first `npm install -g expo-cli eas-cli `

`eas build --platform all`

Right off the bat, we get an error with the Android build related to the lack of an index.js file. It looks like we're supposed to have an index.js file that registers the root and pulls in App.js, like [this](https://github.com/expo/expo/blob/733fe83348e021641e7020edaa659c7ebfeddbe5/templates/expo-template-bare-minimum/index.js). However, I did that, and the app hung on the splash screen, so I obviously did something wrong. Note that I removed the `registerRootComponent` stuff from App.js in my attempt, since that was moved to index.js. I also tried changing the "main" property in package.json.

@bpoore Want to give it a try?

**Comment by bpoore** [comment]
https://github.com/bpoore/pbm-react/commit/073f9a1f5f35c6f1fa9e197912c8a73ce6db74c0

We just needed to change the filename from App.js to index.js 😄 

I was able to generate an Android build that was uploaded to EAS. I wasn't sure of the credentials to be using to generate an Apple build. @RyanTG, if you can give that a shot and let me know if you have any problems?

**Comment by RyanTG** [comment]
You are a genius!

Will give it a shot.

**Comment by RyanTG** [comment]
So I don't forget. The build command will have to include which "build profile" you are using. https://docs.expo.dev/build/eas-json/#build-profiles
That said, our most common build case is to produce signed production builds and then test via testflight/play store. production is the default profile even if you don't use the --profile flag. Sometimes we need to do additional android testing and it's easiest to sideload. In that case, seems like the best thing is to do a "preview" build with apk as the buildType: https://docs.expo.dev/build-reference/apk/

`eas build --profile <profile-name>`
