### ISSUE TITLE
Feature Request: Quicker way to remove machines en masse

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#361]
Use case: location has a lot of machines. Wants a faster way to remove machines en masse.

````
is there any way that when updating a locations games, we could have a select list or highlight feature? One of my home locations has 70+ games and is constantly rotating their lineup. Since the map list is alphabetical and the locations games are not, i have a hard time going down all the rows and being able to see whats changed. If there were a way to select games to “keep at location” and then remove unselected game, it would then be much easier to see whats no longer on the list and add it!

Kind of like group selecting emails to move to a different folder. Something like that. 
````

**Comment by bpoore** [comment]
@RyanTG, do you have thoughts for what this would look like? If we want to afford this behavior as an option to the user, my first thought is that there would be a `bulk delete` option in the location editing tools which would take the user to a screen like what the user sees when they are adding machines to a location when suggesting a location? We could include a bulk add at the same time possibly?

Of note, the API doesn't currently support bulk adding/removing of machines. We can proceed with creating this feature where each addition/removal would be its own request... I presume that won't be a problem for the server, though, the request may take a while if there are huge numbers of additions / removals.

**Comment by bpoore** [comment]
I don't know how often we have issues with people intentionally messing with data in the app, but a `bulk delete` does open us up to someone more easily maliciously clearing out data.

**Comment by RyanTG** [comment]
I do not know how this would look, and I agree that it opens up the risk of malicious behavior. I might start by asking more folks for input (folks who tend to edit the giant locations a lot).
