### ISSUE TITLE
Android text and nav bar theme dark mode.

### ISSUE THREAD

**Issue by ErikGraciosa** [pinballmap/pbm-react#371]
Hi! I've been lurking the project for a while now, even pulled it down months ago but never got it running entirely and I've also been using the map more since pinball is kinda open again.

A feature request I'd like to bring up and potentially help contribute to is in the android dark mode theme. Requesting the header text to be lighter and nav bar to match pinball map dark mode color.
See photos below.
Header text dark, android nav on bottom light.
![image](https://user-images.githubusercontent.com/70562690/129427655-5cd4aae9-e3ab-4194-b57e-1ea6211bcbef.png)

Versus instagram example of light text and dark nav.
![image](https://user-images.githubusercontent.com/70562690/129427691-7d22c7d6-789e-42c4-bf3a-86eb308a9323.png)

**Comment by RyanTG** [comment]
First pull the latest code (or update from the play store). The design has changed since your screenshot. The below screenshot is iOS. The only difference with Android right now is that the map markers are different.

We redid colors in the 5.2.0 release in June. I think they’re higher contrast now.

But let us know what you think! 

![EA97D01B-F1EE-445B-B1DF-A6863A1DA9CB](https://user-images.githubusercontent.com/632682/129427906-c5cf2781-c35a-44a2-a4b8-e9de9276beb0.png)

**Comment by ErikGraciosa** [comment]
Ah, the classic stale version.
Nice the map markers are way easier to discern vs the circles before. Text is easy to read on top. Bottom nav and location modal are light, could change to match dark theme?
![image](https://user-images.githubusercontent.com/70562690/129428468-953c9b85-e967-416b-83fb-df392fb2b923.png)

**Comment by ErikGraciosa** [comment]
Also no problem if not where you're going with the app. Just something I saw as I sit in a dark room contemplating going out in the heat and smoke of Portland :)

**Comment by RyanTG** [comment]
I think the bottom nav color is ok being bright. But yeah, maybe the map callout should have a different color scheme. Cuz that's a big white box.

**Comment by ErikGraciosa** [comment]
Was able to get to these boxes on dark and light. PR submitted but package-lock.json had lots of changes, not sure why.

Also when switching from dark/standard theme the callout will be stale until clicking a different location.
![image](https://user-images.githubusercontent.com/70562690/131424276-8489ee49-fc36-4d9a-8f47-7ef2e3fa9be4.png)
![image](https://user-images.githubusercontent.com/70562690/131424304-811035d0-6702-4c89-9925-c1e906c549b8.png)

**Comment by RyanTG** [comment]
Erik - just as an FYI, I have a decently-sized design refactor in the works (`43 files changed, 466 insertions(+), 413 deletions(-)
` so far). It's mostly related to theme colors. We'll include in our next release - possibly within a week or two. If you're stuff is ready by then, it would be great to include it! Thanks.

I can also push it to master in the next couple days, in case you want to rebase your branch to it.

**Comment by RyanTG** [comment]
I'll think we'll close this in favor of https://github.com/pinballmap/pbm-react/issues/437
