### ISSUE TITLE
Pindigo links on location details

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#381]
Pindigo has locations in their app (which includes data from us). And each location links to the respective pinball map location. Their users have no doubt submitted many locations to pbm. They have a good userbase, and they are in the process of opening up their API.

When their API opens up, we'll be able to use a query like `locationbypbmid` to link to pindigo locations using pbm location IDs.

I envision adding a link to LocationDetails that is similar to the one they have for us: a pindigo icon (either purple or white - or maybe either depending on light/dark mode) situated next to the heart icon. 

In the meantime (before their API is ready), they have said that they could immediately create custom deep links based on our IDs. I'm not sure of their timeline for the new release.

**Comment by bmanturner** [comment]
Brendan from Pindigo here. 

Our website doesn't currently have a dedicated route for viewing a location, so I need to decide on one of a couple options.

- Retrofit a barebones location page into the existing website so I can display something when the user doesn't have Pindigo installed (`https://pindigo.app/pbm/{pbmId}` seems like a good fit and easy for you to generate links to)
- Wait until the new website is in place, which could be a few months

I'm leaning towards the retrofitting, and then accommodating the same link path in the new website. Will update here when I know for certain

**Comment by RyanTG** [comment]
Closing as stale.
