### ISSUE TITLE
iOS requirement - account deletion within apps

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#416]
https://pinballmap.com/users/edit
Is the page with the account deletion link. However, they'd need to be logged in on the website to see that. It doesn't work when you include the user id in there, like https://pinballmap.com/users/13/edit

Not sure what to do. Seems like a website update of some sort is needed.

Quote:

Account deletion within apps
App Store Review Guideline 5.1.1 provides people with greater control over their personal data by stating that all apps that allow for account creation must also allow users to initiate deletion of their account from within the app. This requirement was set to apply to all app submissions by January 31, 2022. Due to the complexity of implementing this requirement, we’ve extended the deadline to June 30, 2022 to give you more time.

Please keep these requirements in mind when updating your app:

- The account deletion option should be easy to find in your app.
- It’s insufficient to only provide the ability to temporarily disable or deactivate an account. People should be able to delete the account along with their personal data.
- Apps in highly-regulated industries may need to provide additional support flows to confirm and facilitate the account deletion process.
- Follow applicable legal requirements for storing and retaining user account information. This includes complying with local laws in different countries or regions. As always, check with your legal counsel.

**Comment by bpoore** [comment]
I'm not sure it's the end of the world to open a link in the app to `https://pinballmap.com/users/edit` and have the user sign in on the site? 

If that is a problem, we could make a screen in the app and make a new endpoint? 
Something like `/api/v1/users/${userId}/edit` along the lines of the exiting [user endpoints](https://pinballmap.com/api/v1/docs/1.0/users.html)?

I'm not promising on a timeline where I'd be involved with making the API endpoint, but if we could get the endpoint created, I could make the app stuff happen.

**Comment by RyanTG** [comment]
On the website, when you log in, it then sends you to the last page you were viewing. However, if you are logged out and you visit `https://pinballmap.com/users/edit` it immediately resolves to `https://pinballmap.com/users/login` (the login screen), but then _doesn't_ redirect you back to that edit page, I think because you didn't technically visit it while logged out.

So from a "making it easy to cancel your account in order to comply with Apple" this current setup might not suffice.

Luckily we have until the end of June to come up with a good solution. I'll look at the endpoints and see if I can make any sense of them.

**Comment by RyanTG** [comment]
I think the solution will be to link to the user's profile page on the website. That page contains a link for deleting your account.

Given that user may not be logged in to the website, they'll still be able to see the user profile page but the "edit/delete" link won't be there. I'll add a link to the "logged out" profile page that says "log in to edit/delete/etc"

Then in the app, I guess this link should be below the Logout button on the user profile page.

I'll start doing this, just so it's ready for the next release. Apple sent me another reminder about it today.

**Comment by RyanTG** [comment]
ok it's on the website and the app PR is here https://github.com/pinballmap/pbm-react/pull/448
