### ISSUE TITLE
Link to App Settings in App

### ISSUE THREAD

**Issue by bpoore** [pinballmap/pbm-react#417]
If a user doesn't have location tracking on, when they press the button to move the map to their current location, we're currently only telling the user they need to go to their device settings and turn on location tracking themselves. We should be able to open the settings app for them.

Resources:
https://docs.expo.dev/versions/latest/sdk/location/#permissionresponse
https://docs.expo.dev/guides/permissions/?redirected
https://medium.com/toprakio/react-native-how-to-open-app-settings-page-d30d918a7f55

**Comment by RyanTG** [comment]
This seems to work on both platforms https://github.com/pinballmap/pbm-react/commit/20501fed44379b6723dcff3456a9130dcd336f5c
