### ISSUE TITLE
Keep events active for longer past their start date

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#455]
A user noted that events were disappearing a few hours before the event started (possibly because of time zone issues). On the website, we retain events for a week after they've occurred. We should do something similar on the app.

**Comment by bpoore** [comment]
Good call! I've noticed this too.

**Comment by bpoore** [comment]
I took a quick look at this. For the site, it appears we are getting the events via a [job](https://github.com/pinballmap/pbm/blob/aff7fd7cbb7d69d8aecd8ce5ee2f8ec53385d308/lib/tasks/import_ifpa_tournaments.rake) that runs and stores the events in our db. It appears the events functionality is only available when associated with regions on the site (?). For the app, we've been hitting the IFPA API directly and it doesn't appear to be an option to select time ranges, so we may need to bug the folks at the IFPA to see what's possible or we may not be able to support this with how the app is using the currently selected map location with a distance radius.

**Comment by RyanTG** [comment]
Update: we have asked the folks at IFPA about this but haven’t received a reply.

**Comment by RyanTG** [comment]
```
About a week or so ago I did change the queries to have a day lag -- but realized I did it on the V2 scanner, so I will add it to the V1 scanner sometime today.

Also, feel free to switch to the V2 API.
```
