### ISSUE TITLE
Placeholder text on search screen about machine filtering

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#457]
Have placeholder text on the search screen saying, "Looking to search by machine? Go back to the map and click Filter"

I think it can be below the search bar and above the "recent searches". And it disappears when you start searching.

**Comment by RyanTG** [comment]
@bpoore I just changed the label on this to 5.2.13 in case it’s something we can slip into the next release. We get asked about ”how to search by machine“ pretty regularly and I think this would really help.

I tried my hand at this a couple months ago but I couldn’t quite figure it out.

**Comment by bpoore** [comment]
Pushed up a[ commit](https://github.com/pinballmap/pbm-react/commit/772d19a15a89d1d5d3411e3081f5ec3ec937c480) to the working branch I have with the other updates we've been working on. Feel free to update styles as you like!
![Simulator Screen Shot - iPhone 11 Pro - 2022-12-05 at 21 38 26](https://user-images.githubusercontent.com/7720282/205826527-a535d633-47ea-4704-add8-1dd4225d5144.png)
