### ISSUE TITLE
Android: textinput is really slow in Android 13

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#464]
Android 13 was just released. We got a user report that the app bogs down bigtime while typing machine comments.

And I saw another report (on an Expo chat) where someone experienced this. So, it might be a known issue. I do not know the solution yet.

Also, I have a feeling that my Android testing phone might be too old to get Android 13. So I might have trouble testing this. But I'll check.

**Comment by RyanTG** [comment]
Notes: Hoping that SDK 47 (with upgrades React and React Native) fixes this. I can't test Android 13 on my phone. We also seem to experiencing other issues with Android 13, but again SDK 47 may help here, and we've also added Sentry support for better debugging.

**Comment by RyanTG** [comment]
Note from Expo discord:

> You could look into how you are using the TextInput. Maybe your already doing this but putting your state text into defaultValue instead of value performs better. That’s if you require no validation or extra work on the state as the user types.

**Comment by RyanTG** [comment]
old issue that still affects people https://github.com/facebook/react-native/issues/20119

**Comment by bpoore** [comment]
Yes, `onChangeText` is updating the component state as each letter is typed. If we want to continue to enforce something is typed prior to being able to [submit a condition](https://github.com/pinballmap/pbm-react/blob/36288a735beab6c2470d88556d7cacba0b6c8c87/app/screens/MachineDetails.js#L149), we will need to keep tracking via state. It looks like we can swap the `value` prop for the `defaultValue` prop. If that does enough to fix our issue, AMAZING, but I would also be surprised if it did. We can give it a shot though. [Branch](https://github.com/pinballmap/pbm-react/tree/remove-value-from-text-input)

**Comment by RyanTG** [comment]
Note: we now have a Android 13 in an emulator, and one more tester (with another to come soon). The emulator and the 2nd tester are _not_ experiencing this issue.

Still unknown if the 1st tester is still experiencing this with the `defaultValue` change.

**Comment by Phong-TH** [comment]
@RyanTG do you have any ideas for this? I have the same issue.

**Comment by RyanTG** [comment]
@Phong-TH You’re experiencing it with our app or your own? If our app, did you upgrade to the version we released yesterday?

If your app, changing the textinput to use defaultValue seems to have fixed it.

**Comment by Phong-TH** [comment]
@RyanTG I have changed the value prop to defaultValue prop, it works fine on the Pixel devices but not on Samsung devices running on Android 13. Our clients are experiencing this issue with our apps.

**Comment by RyanTG** [comment]
Shoot. We haven’t thoroughly tested too many devices, but will check and see if we’re still experiencing this with Samsungs. I know Beth here had an idea about using ref (but she was throwing out ideas and we didn’t try it yet). To quote our private chat:

> let’s try this first approach of removing value and if it’s still not good, I will try to figure out how to target the underlying element containing the text in the text input with a ref

**Comment by Phong-TH** [comment]
@RyanTG We will try this solution: set the value to a ref in `onChangeText` event instead of using `useState`, but we can't test in Samsung devices running on Android 13 right now. Hope it can fix the issue.

**Comment by gkasireddy202** [comment]
@Phong-TH   - Any example?
