### ISSUE TITLE
Include the "Save" heart on the locationCard screen

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#481]
With functionality to heart / un-heart locations.

Thinking the icon location could be to the right of the venue name.

The locationCard is used for "List" and for "Saved." For List, the cards will include venues they have and not hearted. For Saved, it will only include venues that they have hearted. One consideration for Saved is that if a user "un-hearts" a location on their Saved list, should the card disappear right then and there?!

**Comment by bpoore** [comment]
[Branch](https://github.com/pinballmap/pbm-react/tree/fave-location) sans animations. To include custom styles from the location card, they can be passed in as a [style prop](https://github.com/pinballmap/pbm-react/compare/fave-location?expand=1#diff-9281065d25271c98923dbbbd0afb5d471b191d5eb02eb5664efa4a4444c097c1R260). If there are going to be custom styles on press, they can be passed as `pressedStyle` and `notPressedStyle` (unless the styles are the same in all cases we are going to use the component, in that case, we can pull the styles into the component directly)

**Comment by RyanTG** [comment]
Status: I merged this with master. Tweaked some design. When we work on the lottie animations, we can do a new branch.
