### ISSUE TITLE
5.2.18 design notes

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#489]
- [x] add “address” icon https://icons.expo.fyi/MaterialIcons/location-on or https://icons.expo.fyi/Ionicons/location-outline to location card
- [x] Darker address text on location details
- [x] Something with the location name on details. Above map? 
- [x] Smaller map? Like a square next to type container?
- [x] Some more bold colors instead of pale shades. Maybe dark purple? Purple machine names instead of pink? Or something to go with the pink better, like a yellow.
- [x] Location card: remove location name background. Larger name. Left align.
- [ ] Include machine count?
- [x] Consider note to operators on the comment screen about not whitewashing comments.
- [ ] Small increase in zoom out limit 
- [x] Little smaller location name on location details?
- [ ] Little larger machine name on machine details?
- [x] Margin on thank you for confirming message. And check other similar modals.
- [x] Consider removing the button style from pintips and ipdb. Just underline? Or a different color?
- [x] Messages on location edit form about address changes and no machines.
- [x] thanks for submitting margins/colors are way off
- [x] Text on leave a comment and remove machine
- [x] Picture border color

**Comment by RyanTG** [comment]
@bpoore Do you think it would be kewl to show the "machine count" on the Location Details screen? Not exactly sure where, but just wondering if this is a good idea. Same Q for the location card.

Maybe we should just "put a pin in it" and think about this.

**Comment by bpoore** [comment]
That could be cool. Could possibly be conditionally rendered for locations with more than x machines. Would be nice when deeplinking to a specific location especially.
