### ISSUE TITLE
Navigating from "thanks for submitting location" goes to the filled in submission form

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#492]
As a result, some people get confused and submit it again. I think we should be navigating... to the map?

**Comment by RyanTG** [comment]
I thought it might be changing `navigate('Map')` to `navigation.navigate('Map')` at https://github.com/pinballmap/pbm-react/blob/6794e2c1135bbcf375363d1080b567fcbe0ee66d/app/screens/SuggestLocation.js#L179

But that doesn't fix it... ?

**Comment by RyanTG** [comment]
Ok, this seems fixed. Map screen is called MapTab in the navigation! https://github.com/pinballmap/pbm-react/commit/d41366331232c012a11579aafc250c5c8c1822be

Only issue is that the submission form doesn't 100% reset. If you go back to it, the machines you added in your previous submission are still there. I'm not sure how to fix that, but it seems like something we should fix.

(side note: We still use `navigate('Map')` in three places on the map screen. I don't totally understand what is happening in those sections. But should those be changed to `navigate('MapTab')`? And would that fix some of the bugs we're seeing (which seem to be problems related to that section of code - though they seem to have more to do with `region` being undefined. See https://github.com/pinballmap/pbm-react/issues/480).

**Comment by beth-poore** [comment]
Let's prioritize getting meaningful linting into this project. The issue with the form not resetting is back from when the SuggestLocation screen was updated to be a [function component](https://github.com/pinballmap/pbm-react/commit/a7fca517d1c931c5295252c6e5e04acde56c7a0f#diff-b6805ea7e114624509e89a05501a6321ef0a836a30fb4ff7230f61627c52bb7fL118). We were clearing out the pertinent redux state attributes when navigating away from the screen prior to the update. We would have caught this if linting to catch unused functions was in place as the references to `clearSelectedState` still exist for the `SuggestLocation` screen. I will push up a commit to master removing the `clearSelectedState` references and add the attributes to be updated to the appropriate [reducer](https://github.com/pinballmap/pbm-react/blob/master/app/reducers/location.js#L216).

**Comment by bpoore** [comment]
Let's prioritize getting meaningful linting into this project. The issue with the form not resetting is back from when the SuggestLocation screen was updated to be a [function component](https://github.com/pinballmap/pbm-react/commit/a7fca517d1c931c5295252c6e5e04acde56c7a0f#diff-b6805ea7e114624509e89a05501a6321ef0a836a30fb4ff7230f61627c52bb7fL118). We were clearing out the pertinent redux state attributes when navigating away from the screen prior to the update. We would have caught this if linting to catch unused functions was in place as the references to clearSelectedState still exist for the SuggestLocation screen. I will push up a commit to master removing the clearSelectedState references and add the attributes to be updated to the appropriate [reducer](https://github.com/pinballmap/pbm-react/blob/master/app/reducers/location.js#L216).

**Comment by bpoore** [comment]
[fixed](https://github.com/pinballmap/pbm-react/commit/9b4f2a4ecfe81be47bb25f3f2d5178a094e40b52)
