### ISSUE TITLE
If a location in "Recent Search History" has been deleted, clicking it causes a problem

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#496]
I'm assuming we'll need to use the staging service to test this. But I just clicked on a location in my "Recent Search History" that has since been deleted. Clicking on it causes the locationDetails screen to spin. Only the back arrow is present. Clicking the back arrow loads the Map screen, but the map spins, too!! I can click to other screens (like "Saved"), and then load a location. But I still can't recover from the map spinning.

**Comment by bpoore** [comment]
Good catch! Let's get a fix into the next release for this. It shouldn't be happening to too many folks, but that's a lame experience when it does. I will look into it. I imagine we will have an error modal pop up to let the user know we couldn't get the location... shouldn't be too much work. I can probably fake the failed response on my end for the time being.

**Comment by RyanTG** [comment]
https://github.com/pinballmap/pbm-react/commit/cc2eee60629bdaddd04b6bc75ded484d888154af
