### ISSUE TITLE
Stern Insider toggle on machines

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#502]
On the website, we are in the process of adding an Insider Connected toggle. Here's the [working branch](https://github.com/pinballmap/pbm/tree/insider_connected), and here's [the issue](https://github.com/pinballmap/pbm/issues/1328).

**Functionality Overview**

Three new fields:
- **ic_eligible**. Machine field that we - admins - set manually on some stern machines. Boolean field that accepts null/true/false. Defaults to null.
- **ic_enabled**. Machine field that users toggle true/false on machines that have ic_eligible=true. When clicked, this also toggles - if appropriate - the location-level ic_active field described below. Boolean field that accepts null/true/false. Defaults to null.
- **ic_active**. Location field that tracks whether *any* of the machines at the location are ic_enabled. 

**In the app**

For ic_eligible machines, include a toggle button on machineDetails. On the website, I have a single button that has three states: 

"? Insider Connected"
"✓ Insider Connected" and
"X Insider Connected"

Note that ? is an initial null state for ic_enabled on ic_eligible machines. After that, users can only toggle true/false - they can't get back to that null state.

On the website, we aren't displaying "ic_active" anywhere on the location. It's more of a flag that Stern or whoever can use to pull up all the locations with at least one IC machine.

I'll note in this issue when the website functionality is ready.

**Comment by RyanTG** [comment]
This seems to be ready in this branch, but it hasn't been merged upstream yet https://github.com/pinballmap/pbm/tree/insider_connected

Was trying to see if we could get some initial data to populate it.

**Comment by RyanTG** [comment]
I didn't realize that I hadn't updated this issue. This insider connected toggle is **_ready to go_**! As of a week or two ago :D Would be cool to get it in the app fairly soon.

**Comment by RyanTG** [comment]
Question mark icon https://icons.expo.fyi/FontAwesome5/question-circle
Check mark: https://icons.expo.fyi/FontAwesome5/check-circle
X icon: https://icons.expo.fyi/MaterialCommunityIcons/close-circle-outline

Thinking we can put the button above the "machine comments" box.

**Comment by bpoore** [comment]
[Branch](https://github.com/pinballmap/pbm-react/compare/insider-connect?expand=1) where the feature is functioning, but can use some design updates @RyanTG

**Comment by RyanTG** [comment]
It might be easier to record feedback in issues rather than chat. Here is what I just chatted:

If I check a box and then add the machine, and then scroll down the location details and click to the machine details , then it shows "?" instead of the correct status.

However, navigating back to the map and then back the location details again, and then to the machine details, then it shows the correct status.

Also, if I check a box and also add a comment, then click add, then scroll down to the machine details, it shows the correct status

In a way this seems like a ... caching issue?

**Comment by RyanTG** [comment]
Unable to consistently reproduce the above. So... disregard.
