### ISSUE TITLE
Select multiple items in Recent Activity Filter

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#508]
User feedback: would like to be able to select multiple filter items, and not just one.

- Would entail not closing the modal when selecting an item
- Would need to make it clear that users can select multiple. Ideas: a checkbox next to each one. But still highlight the entire list item when selected
- Add a "done" button at the bottom of the list to close the modal

**Comment by RyanTG** [comment]
Regarding the checkbox, RNE has a checkbox https://reactnativeelements.com/docs/components/checkbox and a listItemCheckbox https://reactnativeelements.com/docs/components/listitem_checkbox

If possible, I think we should try to include a checkbox icon in between the filter type icon and the filter type text. And clicking anywhere on a listitem will add a check to the box as well as (perhaps) highlight the entire listItem row.

**Comment by bpoore** [comment]
[branch](https://github.com/pinballmap/pbm-react/compare/recent-activity-filter?expand=1l)
