### ISSUE TITLE
Bug: "two children with the same key" when filtering by machine and location has two versions

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#511]
Steps:

- Filter locations by Machine (example: Foo Fighters)
- If a location on the map has two versions, such as Pro and LE, then the below error occurs. And the venue shows up twice in the List (and probably has two map markers, but it's hard to tell because they are on top of each other). Example: AYCE Gogi in Van Nuys.

> ERROR  Warning: Encountered two children with the same key, `6784`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**Comment by beth-poore** [comment]
The API is returning the same location more than once: [https://pinballmap.com/api/v1/locations/within_bounding_box.json?swlat=34.1298218441[…]156;nelon=-118.39624006301166;by_machine_id=3674;no_details=1](https://pinballmap.com/api/v1/locations/within_bounding_box.json?swlat=34.12982184419582;swlon=-118.49923990666868;nelat=34.27021337941156;nelon=-118.39624006301166;by_machine_id=3674;no_details=1)

**Comment by bpoore** [comment]
The API is returning the same location more than once: [https://pinballmap.com/api/v1/locations/within_bounding_box.json?swlat=34.1298218441[…]156;nelon=-118.39624006301166;by_machine_id=3674;no_details=1](https://pinballmap.com/api/v1/locations/within_bounding_box.json?swlat=34.12982184419582;swlon=-118.49923990666868;nelat=34.27021337941156;nelon=-118.39624006301166;by_machine_id=3674;no_details=1)

**Comment by RyanTG** [comment]
Thanks. Resolved via https://github.com/pinballmap/pbm/commit/47e98904df5da007abafc0498aaa2c5330344b03
