### ISSUE TITLE
Android user reported that km setting is being reset to miles

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#520]
I have no more details than this.

**Comment by RyanTG** [comment]
I got more details, and I can replicate it.

- I did this as a logged in user
- Go to Settings and switch to km.
- Force close app.
- Come back to app like 20 minutes later and then go to Saved (leaving the app for a long enough time seems to be the important part here). The results are in miles now. And the Settings is switched to miles.

**Comment by bpoore** [comment]
[fix](https://github.com/pinballmap/pbm-react/commit/1f78a5e60ba96047958901739714a73a0f7e0829)
