### ISSUE TITLE
Handling of app store reviewers

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#527]
**Issue:**

Both app stores require us to provide user credentials so they can test all functionality. The problem is that they are testing functionality on production data.

**Possible solutions:**

- In the app, detect if the user is X and if so, show them the staging API_URL instead of production. It almost seems like we should add a field to the users table for "tester = true" and use that, given that we probably don't want to hard code a specific user into the app.
- In the API, do some sort of thing that I'm too lazy to type up right now. Might edit later.

**Comment by bpoore** [comment]
[branch](https://github.com/pinballmap/pbm-react/tree/store-testers)
Note, to the .env we need:
STAGING_API_URL
STORE_TESTERS=[username, username]

**Comment by bpoore** [comment]
We may need some additional work to ensure when we swap from prod -> api that the locations rendered exist in staging (i.e. trigger a re-render of the map locations). I didn't run into any issues testing, but could see that being a potential issue.

**Comment by RyanTG** [comment]
No idea what they do, but I think there's a good chance they login when first prompted given that they are starting with a fresh install. I think we just assume this, and if they reject the review then we can go from there.
