### ISSUE TITLE
Bug: If locations have same name, only one shows up in "Recent Searches"

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#528]
# Background

Sometimes locations have the exact same name (such as Round Table Pizza). There are NO cases, though, where the combo of location name + city name is the same. I do data massaging to make sure those combos are always unique. Only the first sentence there is directly relevant to this bug, though...

# Issue

If you search for Round Table Pizza that is in one city, then search for another Round Table Pizza that is in another city, only _one_ of those will be displayed in Recent Searches. That's the bug!

**Comment by bpoore** [comment]
[commit](https://github.com/pinballmap/pbm-react/commit/baf27ed00370ed940f40d1170898b9946de25db4)
