### ISSUE TITLE
Can’t scroll in the location description textbox

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#539]
When editing a location and editing the location notes field, if the existing notes extend beyond the visible textbox window, you can’t scroll to the bottom. 

This isn’t the case on the same field in the location submission form. Might just be a simple param fix.

**Comment by ErikGraciosa** [comment]
Tried to recreate in android and was able to scroll to the bottom when editting location notes.

https://github.com/pinballmap/pbm-react/assets/70562690/6f7a7b37-95e2-475a-a334-33ed1b8ad112

**Comment by RyanTG** [comment]
What about at a location where the location notes already filled in? I’m unable to replicate it if I type in a long note - in that situation it scrolls just fine, like it is correctly aware of the number of lines. But I experience the issue at locations where the description is already long.

Correction: actually, in that case it’s inconsistent. I experience the issue with Star Worlds but not with Revenge Of. Strange…

Star Worlds Arcade https://pinballmap.com/map/?by_location_id=1845

Revenge Of https://pinballmap.com/map/?by_location_id=16910

**Comment by ErikGraciosa** [comment]
On android, I was able to scroll for both of those locations.

**Comment by RyanTG** [comment]
Must be iOS-specific. Beth was able to replicate.

**Comment by RyanTG** [comment]
This seems sufficient https://github.com/pinballmap/pbm-react/commit/0bf046bb6be2d0a4832db2205ab6985c5d606c42

I gave multiline textinputs a minimum height, and made them all grow in height as the content grows.

**Comment by bpoore** [comment]
Confirmed I am not seeing this issue anymore with the update on master. Nice!

**Comment by RyanTG** [comment]
I think we need to revisit this. While the textInput growing in size seems cool, it presents an issue where the input doesn't always successfully avoid the keyboard.

As a result, I think we need to go back to using a fixed height for these inputs. The problem originally found in this issue still persists on iOS, but I have more details.

- It only happens when the value is a single long paragraph - no line breaks.
- It only happens when you are "editing" a textinput that already has content in it (that exceeds the height of the textinput and is one long paragraph).

I feel like the solution is to somehow measure the height of the content when you go to edit the box, because I think that measurement/awareness of the content height is being lost and that's the problem.

**Comment by RyanTG** [comment]
Ok, I resolved it. The problem was with

```
placeholder={description || "Location description..."}
```

I can't say exactly why, but the above looks like the description was being used as a placeholder.

**Comment by RyanTG** [comment]
Oh man. Still an issue.

**Comment by RyanTG** [comment]
Ok, now fixed? https://github.com/pinballmap/pbm-react/commit/fe501db183f3af49928909eaf856b6cc873877e2
