### ISSUE TITLE
Bug: recently searched City that no longer has machines

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#541]
Steps to replicate:
- Search for a city that has a location
- Later on, location is removed from map. But the city is still in your Recent Searches list
- Click it. App spins and has to be force closed.

Seems similar to https://github.com/pinballmap/pbm-react/issues/496

Can set up the Staging server for this. Not easy/safe to test on production!

side note is some users have asked if they could remove items from search history. Maybe with a left swipe? Made an issue for that https://github.com/pinballmap/pbm-react/issues/544

**Comment by bpoore** [comment]
[commit](https://github.com/pinballmap/pbm-react/commit/67e0b20d705176d89c2c0228bb3f03f0ce564bf5)
