### ISSUE TITLE
On the addMachine modal in findMachine, include a backglass image if available

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#542]
To help users figure out if the version they're adding is the correct version, include a backglass image (if available) on that "confirm adding a machine" modal.

**Comment by RyanTG** [comment]
https://github.com/pinballmap/pbm-react/commit/b556e089213f6fc3662c6cfc4eca51685b42188a

Seems good. I see a jitter sometimes as the image loads. Not sure if I did something wrong there.

Had to make the modal vertical aligned to the top, rather than center, and then I just shoved in some top margin.

**Comment by bpoore** [comment]
Looks awesome- combined the uses into a [single component](https://github.com/pinballmap/pbm-react/commit/5cd66fc107192879c4a5a2334b4159e3e8867a0b). Helps clear some stuff out of FineMachine and MachineDetails
