### ISSUE TITLE
Include scroll to top on location details screen

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#543]
For parity with the website, it could be useful to show a "scroll to top" button in the lower right of location details.

- Hide if at the top. Only show if user has scrolled down
- One of these seem to be the function:
- https://reactnavigation.org/docs/use-scroll-to-top/
- or maybe https://shopify.github.io/flash-list/docs/usage/#scrolltoindex and set the index to the first item?

Any other screens that could benefit from this? The Find... screens have a fixed thing up top, so might not need to jump to top.

**Comment by bpoore** [comment]
Starting to look at this. Will take a bit of refactoring. useScrollToTop is a hook available for pressing a tab, which this screen does not have. We can utilize scroll to index functions for flatlist or flashlist, but it will require updating the screen to utilize one of those components. To get the scrolling to work as expected, we need to put the list content in the render method and the rest of the content in the `ListHeaderComponent`. Have started in on this, but of course this is also still a class based component.... will get there, just still don't have a ton of time yet 😅

**Comment by bpoore** [comment]
[branch](https://github.com/pinballmap/pbm-react/compare/scroll-to-top?expand=1) for you to play with @RyanTG 


https://github.com/pinballmap/pbm-react/assets/7720282/7421d76f-bfd5-41f8-ac67-f61e07c1def7

**Comment by RyanTG** [comment]
Seems great! I haven't tested on android yet. I added some style (up arrow, no text).
