### ISSUE TITLE
Remove an item from search history, or clear all

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#544]
Seems doable with gesture handler and reanimated. https://blog.logrocket.com/react-native-gesture-handler-swipe-long-press-and-more/

**Comment by RyanTG** [comment]
Also, would be cool to have a button at the bottom for clearing all history.

**Comment by RyanTG** [comment]
Also, would be good to automatically remove an item that is resulting in an error. Like a City or Location that's been removed.

**Comment by bpoore** [comment]
I think we do need to go the route of gesture handling via a swipe or something with how the entirety of the search history rows currently being pressable if we want to allow users to delete a single row.
