### ISSUE TITLE
If "contact" link is clicked from "edit location info" screen, pass in the location name

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#550]
We really often get contact messages where people don't state what location they're talking about. After asking a few people, it's because they all assume the app knows what location they were looking at prior to that.

It's clear that people are not going to manually type in the location name - most are not reading our fine print asking them to do so.

Thinking about possible solutions:

- If "contact" link is clicked from "edit location info" screen, can we pass in the location name and add that to the contact form body?
- Not sure what other ideas...

**Comment by bpoore** [comment]
How do you view the messages coming in from contact us? We can append to the message the location name. Would adding a couple new lines before the location at the end make sense? Or would you rather no new line chars? If you want it as a different attribute of the request body, we can do that too, but might require work on the API end to consume it.

```
{"email": "", "lat": 45.46765555629063, "lon": -122.75617979418726, "messageWithLocationName": "Test with location 

 The Old Market Pub & Brewery", "name": "", "user_email": "beth.poore@gmail.com", "user_token": "MUd1nGKRN_YtmGCxm6AP"}
```

**Comment by RyanTG** [comment]
> How do you view the messages coming in from contact us?

Via email, usually. From this mailer: https://github.com/pinballmap/pbm/blob/master/app/views/admin_mailer/send_admin_notification.html.haml

Which contains user.username, user.email, and message fields (if user is logged in).

Appended to the message is totally fine. And new lines are totally fine (assuming they are correctly consumed by the mailer - but if not, we can tweak).

**Comment by bpoore** [comment]
With how string interpolation is occurring via the mailer, we are not currently getting the new line characters (I tried a few ways to see if we could get new lines in there, but no dice). Would you rather we add a new attribute for the mailer to have a new field or would just including the location name at the end of the message be sufficient? We can add more characters or whatever will make this easiest to consume for you if we go the route of just adding to the end of the message.

<img width="494" alt="Screenshot 2024-05-06 at 12 34 01 PM" src="https://github.com/pinballmap/pbm-react/assets/7720282/e6c69c61-51b7-419c-9cea-064e56d6fa5a">

**Comment by bpoore** [comment]
[commit](https://github.com/pinballmap/pbm-react/commit/90efc5a7c042795fcc19df9fcf33480817829e4a)
