### ISSUE TITLE
Share button should be top level

### ISSUE THREAD

**Issue by Kadajett** [pinballmap/pbm-react#552]
To drive more users to locations and to the app, the share button should be readily available on the location page of the mobile app.

Sorry if this isn't the right repo. Learning the codebase now! 

![Uploading Screenshot_20240516-192507.png…]()

**Comment by RyanTG** [comment]
Thanks. This is the right place. We can look into moving buttons around. We used to have the Share at the top level.

We might even be able to get rid of that extra menu entirely. Some items in it are duplicates. And others could be top level. The main one I’m concerned about is “confirm line-up” - that one is used often, but is not intuitive without the text describing it, and I’m hesitant to add more text to the top level. Maybe it could be just a button, but with a “confirm modal” that explains what it is and gives the user an option to cancel.

Can’t tell if there was supposed to be an image in this issue. On my phone I see a blank box of some sort.

**Comment by RyanTG** [comment]
I'm going to work on this today (wasn't sure if you were planning to, but I can knock it out).

**Comment by RyanTG** [comment]
Draft. And the “edit location details” button is tucked within the location details section.
![IMG_0648](https://github.com/pinballmap/pbm-react/assets/632682/d671c072-1f4a-4c38-ab42-2d31a6fca707)
